services:
  proxy:
    image: nginx:1.28-alpine-slim
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./private:/etc/nginx/private:ro
